### ISSUE TITLE
crash on initial connection

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit_android#41] opened 2018-04-19 17:41 UTC
After a few failed attempts (wrong URL) I got it right and the app connected started spinning its wheel. I looked away for a bit but when I looked back, the app had closed and was also not in the android "recent" app list.

Logcat: https://gist.github.com/ahayes/1421606c3469dd40083618f4c63141cb

**Comment by ahayes** [comment] 2018-04-19 18:28
Pixel C tablet Android 8.1.0

**Comment by grrrian** [comment] 2018-06-20 12:36
Unable to reproduce. I do not see anything suspicious in the logs. Closing issue for now, please re-open with reproduction steps if it happens again ;)

**Closed as completed** 2018-06-20 12:37 UTC
Labels: bug
